version: '3'

services:
  web:
    build: .
    command:
      - /bin/sh
      - -c
      - |
        echo "sleep for 10sec"
        sleep 10
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000

    env_file:
      - .env
    volumes:
      - .:/web_Welltory
    ports:
      - '8000:8000'
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: 'db_Welltory'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    volumes:
      - ./db_django:/var/lib/mysql/
    restart: always