# Generated by Django 3.2.8 on 2022-01-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welltory_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_from_users',
            name='date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
