# Generated by Django 3.2.8 on 2022-01-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welltory_test', '0002_alter_data_from_users_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_from_users',
            options={'ordering': ('id',), 'verbose_name': 'Данные', 'verbose_name_plural': 'Данные'},
        ),
        migrations.RenameField(
            model_name='data_from_users',
            old_name='date',
            new_name='date_pulse',
        ),
        migrations.AddField(
            model_name='data_from_users',
            name='date_steps',
            field=models.DateField(default='2022-01-13', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data_from_users',
            name='date_temperature',
            field=models.DateField(default='2022-01-13', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
