# Generated by Django 3.2.8 on 2022-01-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welltory_test', '0002_alter_data_from_users_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_from_users',
            name='pulse',
            field=models.FloatField(verbose_name='Пульс'),
        ),
        migrations.AlterField(
            model_name='data_from_users',
            name='steps',
            field=models.FloatField(verbose_name='Количество шагов'),
        ),
        migrations.AlterField(
            model_name='data_from_users',
            name='temperature',
            field=models.FloatField(verbose_name='Температура'),
        ),
    ]
