# Generated by Django 3.2.8 on 2022-01-11 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welltory_test', '0003_auto_20220111_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_from_users',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
