# Generated by Django 3.2.8 on 2022-01-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welltory_test', '0003_auto_20220113_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_from_users',
            options={'ordering': ('created_at',), 'verbose_name': 'Данные', 'verbose_name_plural': 'Данные'},
        ),
        migrations.AddField(
            model_name='data_from_users',
            name='Pearson_count',
            field=models.FloatField(default=0.5, verbose_name='Pearson'),
            preserve_default=False,
        ),
    ]
