# Generated by Django 3.2.8 on 2022-01-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welltory_test', '0004_auto_20220114_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_from_users',
            name='Pearson_count',
            field=models.TextField(verbose_name='Pearson'),
        ),
    ]
