# Generated by Django 3.2.8 on 2022-01-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welltory_test', '0006_alter_data_from_users_pearson_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_from_users',
            name='Pearson_count',
            field=models.CharField(blank=True, default=True, max_length=300, null=True),
        ),
    ]
