# Generated by Django 3.2.8 on 2022-01-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welltory_test', '0010_data_from_users_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_from_users',
            name='title',
            field=models.CharField(blank=True, default='Мои данные', max_length=20, verbose_name='Название'),
        ),
    ]
