# Generated by Django 3.2.8 on 2022-01-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welltory_test', '0011_alter_data_from_users_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_from_users',
            name='Pearson_count',
            field=models.FloatField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data_from_users',
            name='pulse',
            field=models.FloatField(blank=True, default=500, verbose_name='Пульс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data_from_users',
            name='steps',
            field=models.FloatField(blank=True, default=1000, verbose_name='Количество шагов'),
            preserve_default=False,
        ),
    ]
