# Generated by Django 3.2.8 on 2022-01-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welltory_test', '0012_auto_20220119_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_from_users',
            name='title',
            field=models.CharField(blank=True, max_length=20, verbose_name='Название'),
        ),
    ]
