# Generated by Django 3.2.8 on 2022-01-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welltory_test', '0013_alter_data_from_users_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_from_users',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
