# Generated by Django 3.2.8 on 2022-01-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welltory_test', '0014_alter_data_from_users_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_from_users',
            name='Pearson_count',
            field=models.FloatField(blank=True, default=None, max_length=30),
        ),
    ]
