# Generated by Django 3.2.8 on 2022-01-31 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('welltory_test', '0015_alter_data_from_users_pearson_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_from_users',
            name='temperature',
            field=models.FloatField(blank=True, default=django.utils.timezone.now, verbose_name='Температура'),
            preserve_default=False,
        ),
    ]
